client_config_backend: settings
client_config:
    client_id: 470632948954-p1u40nlo3tns5udih46elb3et216abm1.apps.googleusercontent.com
    client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials_module,json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive